import {test} from 'node:test';
import assert from 'node:assert/strict';
import {daysTogether,escapeHTML} from '../src/model.js';
test('anniversary uses local calendar days, inclusive',()=>{assert.equal(daysTogether('2026-09-04',new Date(2026,8,5,0,1)),2);assert.equal(daysTogether(null),0);assert.equal(daysTogether('2027-01-01',new Date(2026,8,5)),0);});
test('private messages render as text rather than executable HTML',()=>assert.equal(escapeHTML('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;'));
import {readInvite,explainError,localDate} from '../src/model.js';
test('invitation parsing accepts only a UUID or a valid invite URL',()=>{const token='896ff375-2ddb-4369-941c-8062040d3d0a';assert.equal(readInvite('https://example.com/nest/#invite='+token),token);assert.equal(readInvite('import evil from "code"'), '');assert.equal(readInvite('bad-token'),'');});
test('configuration and account errors are actionable',()=>{assert.match(explainError({code:'PGRST205'}),/schema.sql/);assert.match(explainError({code:'email_not_confirmed'}),/确认邮件/);assert.match(explainError({status:429}),/60/);});
test('date input has a locale-independent value',()=>assert.equal(localDate(new Date(2026,8,6)),'2026-09-06'));
import {validatePhoto} from '../src/model.js';
test('photo validation rejects unsupported and oversized files',()=>{assert.throws(()=>validatePhoto({type:'image/svg+xml',size:100}),/JPG/);assert.throws(()=>validatePhoto({type:'image/jpeg',size:6*1024*1024}),/5 MB/);assert.doesNotThrow(()=>validatePhoto({type:'image/png',size:2048}));});
